const menuJson = [
    {
        "id": 1,
        "nombre": "plato1",
        "ingredientes": ["ing1","ing2","ing3", "ing4", "ing5"],
        "precio": 1000,
    },
    {
        "id": 2,
        "nombre": "plato2",
        "ingredientes": ["ing1","ing2","ing3", "ing4", "ing5"],
        "precio": 1000,
    },
    {
        "id": 3,
        "nombre": "plato3",
        "ingredientes": ["ing1","ing2","ing3", "ing4", "ing5"],
        "precio": 1000,
    },
    {
        "id": 4,
        "nombre": "plato4",
        "ingredientes": ["ing1","ing2","ing3", "ing4", "ing5"],
        "precio": 1000,
    },
    {
        "id": 5,
        "nombre": "plato5",
        "ingredientes": ["ing1","ing2","ing3", "ing4", "ing5"],
        "precio": 1000,
    },
    {
        "id": 6,
        "nombre": "plato6",
        "ingredientes": ["ing1","ing2","ing3", "ing4", "ing5"],
        "precio": 1000,
    },
    {
        "id": 7,
        "nombre": "plato7",
        "ingredientes": ["ing1","ing2","ing3", "ing4", "ing5"],
        "precio": 1000,
    },
    {
        "id": 8,
        "nombre": "plato8",
        "ingredientes": ["ing1","ing2","ing3", "ing4", "ing5"],
        "precio": 1000,
    },
    {
        "id": 9,
        "nombre": "plato9",
        "ingredientes": ["ing1","ing2","ing3", "ing4", "ing5"],
        "precio": 1000,
    },
    {
        "id": 10,
        "nombre": "plato10",
        "ingredientes": ["ing1","ing2","ing3", "ing4", "ing5"],
        "precio": 1000,
    },
    {
        "id": 11,
        "nombre": "plato11",
        "ingredientes": ["ing1","ing2","ing3", "ing4", "ing5"],
        "precio": 1000,
    },
    {
        "id": 12,
        "nombre": "plato12",
        "ingredientes": ["ing1","ing2","ing3", "ing4", "ing5"],
        "precio": 1000,
    },
    {
        "id": 13,
        "nombre": "plato13",
        "ingredientes": ["ing1","ing2","ing3", "ing4", "ing5"],
        "precio": 1000,
    },
    {
        "id": 14,
        "nombre": "plato14",
        "ingredientes": ["ing1","ing2","ing3", "ing4", "ing5"],
        "precio": 1000,
    },
    {
        "id": 15,
        "nombre": "plato15",
        "ingredientes": ["ing1","ing2","ing3", "ing4", "ing5"],
        "precio": 1000,
    },
    {
        "id": 16,
        "nombre": "plato16",
        "ingredientes": ["ing1","ing2","ing3", "ing4", "ing5"],
        "precio": 1000,
    },
    {
        "id": 17,
        "nombre": "plato17",
        "ingredientes": ["ing1","ing2","ing3", "ing4", "ing5"],
        "precio": 1000,
    },
    {
        "id": 18,
        "nombre": "plato18",
        "ingredientes": ["ing1","ing2","ing3", "ing4", "ing5"],
        "precio": 1000,
    },
    {
        "id": 19,
        "nombre": "plato19",
        "ingredientes": ["ing1","ing2","ing3", "ing4", "ing5"],
        "precio": 1000,
    },
    {
        "id": 20,
        "nombre": "plato20",
        "ingredientes": ["ing1","ing2","ing3", "ing4", "ing5"],
        "precio": 1000,
    }
];